### ISSUE TITLE
Current Ubuntu 14.04 uses kernel with degraded disk performance in SMP environment

### ISSUE THREAD

**Issue by mfn** [jedi4ever/veewee#1015]
Not sure if this can be considered as a bug per se, but here's a heads up anyway.

I discovered that the Ubuntu Server 14.04 amd64 ISO image currently used by the template ( https://github.com/jedi4ever/veewee/blob/8a4323471a6a4705799b3920ab01519c65dd55b7/templates/ubuntu-14.04-server-amd64/definition.rb#L9 ) uses a kernel which is compiled with the `CONFIG_CONTEXT_TRACKING_FORCE` set to `y`.

This leads to the following disk performance degraded in SMP environments (i.e. more than one CPU):

```
vagrant@ubuntu-14:~$ dd if=/dev/zero of=bigfile bs=1024 count=5000000
5000000+0 records in
5000000+0 records out
5120000000 bytes (5.1 GB) copied, 46.6511 s, 110 MB/s
```

For comparison, a kernel which has this flag disabled/removed (and uses multiple CPUs):

```
vagrant@ubuntu-14:~$ dd if=/dev/zero of=bigfile bs=1024 count=5000000
5000000+0 records in
5000000+0 records out
5120000000 bytes (5.1 GB) copied, 10.4548 s, 490 MB/s
```

Took me a while to figure this out, here are the resources I used to figure thus out:
- [My Superuser Question, answered with my solution](http://superuser.com/questions/835399/ubuntu-server-14-04-in-virtualbox-disk-performance-drops-with-more-than-1-cpu)
- [Post in virtualbox forum,  self-answered](https://forums.virtualbox.org/viewtopic.php?f=3&t=64468&p=304068#p304068)
- [Ubuntu bug report, again self-answered](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1390354)
- [Information about the CONFIG_CONTEXT_TRACKING_FORCE flag](http://cateee.net/lkddb/web-lkddb/CONTEXT_TRACKING_FORCE.html)
- [Another Ubuntu report which indicates this flag has been changed in recent kernel and is fixed/soon to be released](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1349028)

YMMV

**Comment by darkn3rd** [comment]
Would `sudo apt-get dist-upgrade` resolve this?

**Comment by mfn** [comment]
`¯\_(ツ)_/¯`

I moved on and am now using https://github.com/chef/bento . Over the past two years, in my experience, this was the most reliable (and easiest) way to build generic as well as specialized boxes.

**Comment by mfn** [comment]
Closing, as this issue isn't relevant to me anymore (not using 14.04)
