### ISSUE TITLE
Issues with bundle install

### ISSUE THREAD

**Issue by jordant** [jedi4ever/veewee#1029]
Since commit 1f9fc4d7e0b2e91de1e58d29abeeceedd908053e , bundle install no longer works. Test OS is a fresh ubuntu 14.04 install but I have also tried 12.04. The only way I can get this to work is by using RVM like the travis tests do.

vagrant@ubuntu-trusty:~$ git clone https://github.com/jedi4ever/veewee.git
Cloning into 'veewee'...
vagrant@ubuntu-trusty:~$ cd veewee
vagrant@ubuntu-trusty:~/veewee$ bundle install
There was a NoMethodError while loading veewee.gemspec:
undefined method `metadata=' for #<Gem::Specification name=veewee version=0.5.0.alpha4> from
  /home/vagrant/veewee/veewee.gemspec:59:in `block in <main>'

vagrant@ubuntu-trusty:~/veewee$ bundle --version
Bundler version 1.7.12
vagrant@ubuntu-trusty:~/veewee$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
vagrant@ubuntu-trusty:~/veewee$ gem --version
1.8.23
vagrant@ubuntu-trusty:~/veewee$

**Comment by chrisRidgers** [comment]
same issue on OS X yosemite

**Comment by mayank-io** [comment]
+1

**Comment by nitrocode** [comment]
I also see this error on ubuntu 14.04 server.

**Comment by waffletower** [comment]
Seen same error on Ubuntu 14.04 server and on OS X Yosemite :(

**Comment by jordant** [comment]
Fix for this is to use ruby > 2.x and rubygems > 1.9.0
