### ISSUE TITLE
Vmware Fusion Try II Still doesn't compile images

### ISSUE THREAD

**Issue by symgryph** [jedi4ever/veewee#1031]
/Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/fission-0.5.0/lib/fission/vm.rb:528:in `all_running': uninitialized constant Fission::Action (NameError)
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/fission-0.5.0/lib/fission/vm.rb:405:in `running?'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/fission-0.5.0/lib/fission/vm.rb:326:in `state'
	from /Users/tjmunn/veewee/lib/veewee/provider/vmfusion/box/destroy.rb:11:in `destroy'
	from /Users/tjmunn/veewee/lib/veewee/provider/core/box/build.rb:28:in `kickstart'
	from /Users/tjmunn/veewee/lib/veewee/provider/core/box/build.rb:113:in `build'
	from /Users/tjmunn/veewee/lib/veewee/provider/vmfusion/box/build.rb:9:in `build'
	from /Users/tjmunn/veewee/lib/veewee/command/fusion.rb:23:in `build'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/tjmunn/veewee/bin/veewee:24:in `<top (required)>'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/bin/veewee:23:in `load'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/bin/veewee:23:in `<main>'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tjmunn/.rvm/gems/ruby-1.9.3-p547@veewee/bin/ruby_executable_hooks:15:in `<main>'

I did try rebuilding using the 'rvm' method with what seems to be the 'default' version of ruby 1.93. Gets farther than before, at least downloads the ISos then dies a horrid death.

**Comment by n0ts** [comment]
I think same issue as #1023.

**Comment by mpapis** [comment]
should be fixed already, please try with the latest development version
