### ISSUE TITLE
Copy files used for build

### ISSUE THREAD

**Issue by ghola** [jedi4ever/veewee#1062]
At a point during the build process, veewee copies some files from the host into the VM (postinstalls scripts among others).  Is there a way to ask veewee to copy other files as well? (maybe a way to configure a list of files to be copied within definition.rb).

My use case is that i have some precompiled binaries that i want to inject into the machine before the postinstall scripts start. Atm my workaround is to make a git repo (for example on github), put the needed files into that repo and then have one of the postinstalls scripts clone that repo thus downloading the files into the VM. You can see how this is rather tedious and that for any additional file you need to add/commit/push and then start the build.

**Comment by mpapis** [comment]
like this? => https://github.com/jedi4ever/veewee/blob/master/doc/build_hooks.md#---upload-arbitrary-files---

**Comment by ghola** [comment]
Exactly like that! I searched the docs but failed to hit that page (i probably expected it to be listed among the more general/common options).
Thank you very much.
