### ISSUE TITLE
Add "rvm get stable --auto-dotfiles" to the rvm install docs prior to "rvm use"

### ISSUE THREAD

**Issue by nitrocode** [jedi4ever/veewee#1075]
Please add the following before the "rvm use" command. 

    rvm get stable --auto-dotfiles

You may have to also run `/bin/bash --login`

Source: http://stackoverflow.com/questions/9336596/rvm-installation-not-working-rvm-is-not-a-function

Otherwise you'll get the following error message:

    $ rvm use ruby@veewee --create
    
    RVM is not a function, selecting rubies with 'rvm use ...' will not work.
    
    You need to change your terminal emulator preferences to allow login shell.
    Sometimes it is required to use `/bin/bash --login` as the command.
    Please visit https://rvm.io/integration/gnome-terminal/ for an example.

**Comment by mpapis** [comment]
as there is no active development on RVM 1.x it would be better to use `rvm get master --auto-dotfiles`

also can you open a PR for that?

**Comment by nitrocode** [comment]
Sure.

https://github.com/jedi4ever/veewee/commit/3a9007016d805cb333ed5d65b673cb47a5aa125c
