### ISSUE TITLE
Have Veewee download additional files?

### ISSUE THREAD

**Issue by courtney-miles** [jedi4ever/veewee#1093]
Is there a way to have Veewee download additional files for use during installation?

Specifically I would like to use this in the Gentoo template.  Veewee downloads the relevant ISO just once, but the installation process requires a tar.bz file which is 240 MB.

I'm trying to fix a few things in the Gentoo template and having to wait for the 240 MB tar.bz file to download each time is time consuming on my connection.

I was hoping Veewee might be able to download this in advanced, much like it does with the ISO, only downloading it if it does not exists, and then make it available to the virtual box.

I'm not sure if that's feasible or not.

**Comment by courtney-miles** [comment]
I think I found my answer at https://github.com/jedi4ever/veewee/blob/master/doc/build_hooks.md

**Comment by mpapis** [comment]
yep, use `before_create` to check if file exist and download it or give instructions how to download it, and use `after_postinstall` to upload it to the VM
