### ISSUE TITLE
Any template for Debian9?

### ISSUE THREAD

**Issue by rhtyd** [jedi4ever/veewee#1106]
All, have anyone created a template for debian 9.1 iso yet?

**Comment by FunTimeCoding** [comment]
No. But I can probably do that tomorrow.

**Comment by FunTimeCoding** [comment]
Current status: I did create a branch and copied the 8.2 template to 9.1, but the preseed.cfg needs to be changed or else the setup will open a user prompt for additional downloads. Need to find out what option that is.

**Comment by rhtyd** [comment]
Thanks @FunTimeCoding I don't have the preseed expertise so cannot help, however can help test. Looking forward to your changes.

**Comment by FunTimeCoding** [comment]
#1107

**Comment by rhtyd** [comment]
Thanks I tried the changes @FunTimeCoding it seems to work for me, since we've a PR I'll close this issue now.
