### ISSUE TITLE
i have got this error creating virtualmechine in oracle virtual box please help me out on tnis

### ISSUE THREAD

**Issue by vamsik10** [jedi4ever/veewee#1109]
there was an error while executing 'vboxmanage', a CLI used by vagrant for controling virtual box,  the commond and stderr is shown below

command : [ "startvm", "824037db-6863-4c2e-922f-3b93c5abbea5", "--type","headless"]
stderr; vboxmanage: error : AMD-V is not available (VERR_SVM_NO_SVM)
vboxmanage:error: details: codse NS_ERROR_FAILURE (0X80004005),component   consolewrap, interface iconsole

**Comment by FunTimeCoding** [comment]
It's most likely a BIOS setting that must be enabled. If not, your CPU model might not support virtualization.

**Comment by FunTimeCoding** [comment]
I think you should be able to reopen this if it's still relevant.
