### ISSUE TITLE
hang in mount iso

### ISSUE THREAD

**Issue by larrycai** [jedi4ever/veewee#143]
I reuse the https://github.com/jedi4ever/veewee/blob/master/templates/openSUSE-11.4-DVD-x86_64/definition.rb as template to define my SuSE-SLES-11-SP1 installation, and changed to correct iso files and md5 value.

Unfortunately it always hang when mounting.

    rdccaiy@ubuntu :~/veewee$ vagrant basebox build susesles-11.1-64
    Verifying the isofile SLES-11-SP1-DVD-x86_64-GM-DVD1.iso is ok.
    We found no good state so we are destroying the previous machine+disks
    VBoxManage unregistervm  'susesles-11.1-64' --delete
    Deleting vm susesles-11.1-64
    Creating vm susesles-11.1-64 : 512M - 1 CPU - OpenSUSE_64
    Creating new harddrive of size 20480
    VBoxManage createhd --filename '/home/rdccaiy/VirtualBox VMs/susesles-11.1-64/susesles-11.1-64.vdi' --size '20480' --format vdi > /dev/null
    Attaching disk: /home/rdccaiy/VirtualBox VMs/susesles-11.1-64/susesles-11.1-64.vdi
    Mounting cdrom: /home/rdccaiy/veewee/iso/SLES-11-SP1-DVD-x86_64-GM-DVD1.iso

In another console, I use strace

    rdccaiy@ubuntu:~/vagrant/suse64$ sudo strace -p 822 -i -r -v
    Process 822 attached - interrupt to quit
         0.000000 [b77c7424] restart_syscall(<... resuming interrupted call ...>^C <unfinished ...>
    Process 822 detached

Environment

    Vagrant 0.8.7
    veewee 0.2.0
    Ubuntu 11.04
    Virtualbox 4.1.2 r73507

It works when I create other ubuntu vagrant box, thanks

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
