### ISSUE TITLE
Default hostiocache to on?

### ISSUE THREAD

**Issue by ferlatte** [jedi4ever/veewee#305]
It seems that using turning the hostiocache off in Virtualbox is an optimization that makes veewee not work reliably on Mac OS hosts.

Would it make sense to turn hostiocache on by default so that veewee will Just Work everywhere and let folks who want the optimization turn it back off for their environments?

Alternatively, would it make sense for veewee to "fixup" definitions based on what makes sense for the host OS?

I just spent the day fighting with this, and here's another person who did the same:

http://groups.google.com/group/vagrant-up/browse_thread/thread/28ad2f3807c07c9b

I'm happy to make a patch and pull request if this is a desirable fix.

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
