### ISSUE TITLE
Error when building basebox.

### ISSUE THREAD

**Issue by maraca** [jedi4ever/veewee#446]
The GuestAdditions aren't downloaded automatically, and when I download them manually and add them to the iso folder, I get the following error message.

> veewee vbox build 'derp' --debug  --force
> Building Box derp with Definition derp:
> - force : true
> - debug : true
> - nogui : false
> - auto : false
> - redirectconsole : false
> - postinstall_include : []
> - postinstall_exclude : []

The isofile ubuntu-12.04.1-server-amd64.iso already exists.
VBoxManage unregistervm  "derp" --delete
Deleting vm derp
Creating vm derp : 2048M - 1 CPU - Ubuntu_64
Creating new harddrive of size 10140, format VDI, variant Standard 
Attaching disk: /home/martin/VirtualBox VMs/derp/derp.vdi
Mounting cdrom: /home/martin/code/chef-repo/vagrant/iso/ubuntu-12.04.1-server-amd64.iso
Mounting guest additions: /home/martin/code/chef-repo/vagrant/iso/VBoxGuestAdditions_4.1.12.iso
Error: We executed a shell command and the exit status was not 0
- Command :VBoxManage storageattach "derp" --storagectl "IDE Controller" --type dvddrive --port 1 --device 0 --medium "/home/martin/code/chef-repo/vagrant/iso/VBoxGuestAdditions_4.1.12.iso".
- Exitcode :1.
- Output   :
  VBoxManage: error: Could not get the storage format of the medium '/home/martin/code/chef-repo/vagrant/iso/VBoxGuestAdditions_4.1.12.iso' (VERR_NOT_SUPPORTED)
  VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component Medium, interface IMedium, callee nsISupports
  Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, AccessMode_ReadWrite, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 210 of file VBoxManageDisk.cpp
  VBoxManage: error: Invalid UUID or filename "/home/martin/code/chef-repo/vagrant/iso/VBoxGuestAdditions_4.1.12.iso"

Wrong exit code for command VBoxManage storageattach "derp" --storagectl "IDE Controller" --type dvddrive --port 1 --device 0 --medium "/home/martin/code/chef-repo/vagrant/iso/VBoxGuestAdditions_4.1.12.iso"

**Comment by courtney-miles** [comment]
> ```
> VBoxManage: error: Could not get the storage format of the medium '[...].iso' (VERR_NOT_SUPPORTED)
> ```
> What could be the issue?

This is late, but for anyone who might ask the same question, it might be that your ISO did not fully download.
