### ISSUE TITLE
Kernel panic on 'export'

### ISSUE THREAD

**Issue by dysinger** [jedi4ever/veewee#486]
This just started happening & I'm not sure why. I have a project where I'm perfecting the veewee build of NixOS http://github.com/dysinger/nixbox

I can build the image just fine

![1-build](https://f.cloud.github.com/assets/447/80650/b6d892ca-627c-11e2-8b14-b72ec29522c4.png)

It validates

![1-validate](https://f.cloud.github.com/assets/447/80651/bf616142-627c-11e2-9219-2c120d7c3219.png)

but then I go to export it and it's panicking

![3-export](https://f.cloud.github.com/assets/447/80652/ca7e56de-627c-11e2-97b5-8031eb112d70.png)

This directory /media/sf_veewee_validation is always present after building the box.

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
