### ISSUE TITLE
ruby-libvirt build problem on RHEL6.3

### ISSUE THREAD

**Issue by msuhovec** [jedi4ever/veewee#510]
I am trying to build veewee on a KVM-enabled RHEL6 machine,  2.6.32-279.19.1.el6.x86_64.

Following the instructions on https://github.com/jedi4ever/veewee/blob/master/doc/installation.md,

I install rvm via the rvm-installer

Install ruby 1.9.2p320 via rvm

git clone https://github.com/jedi4ever/veewee.git

cd veewee

gem install bundle

bundle install --without restrictions

The build for this blows up on 

Installing ruby-libvirt (0.4.0) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /global/home/msuhovec/.rvm/rubies/ruby-1.9.2-p320/bin/ruby extconf.rb 
```

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/global/home/msuhovec/.rvm/rubies/ruby-1.9.2-p320/bin/ruby
    --with-libvirt-include
    --without-libvirt-include
    --with-libvirt-lib
    --without-libvirt-lib
    --with-libvirt-config
    --without-libvirt-config
    --with-pkg-config
    --without-pkg-config
extconf.rb:83:in `<main>': libvirt library not found in default locations (RuntimeError)

I have libvirt installed:

rpm -qa | grep libvirt
libvirt-client-0.9.10-21.el6_3.7.x86_64
libvirt-qmf-0.3.0-8.el6_3.x86_64
fence-virtd-libvirt-qpid-0.2.3-9.el6.x86_64
libvirt-python-0.9.10-21.el6_3.7.x86_64
libvirt-0.9.10-21.el6_3.7.x86_64
fence-virtd-libvirt-0.2.3-9.el6.x86_64

I can build it if I leave off the --without restriction, but I'd like to use KVM.

IS this a know issue, or some config error on my part?

Mark

**Comment by Shumakriss** [comment]
yum install libvirt-devel in Fedora 21 works for me!

**Comment by Markieta** [comment]
`sudo dnf install libvirt-devel` also worked for me on Fedora 22.

**Comment by shaileesheth** [comment]
:+1:

**Comment by jcoffland** [comment]
I have ``libvirt-dev`` installed on Debian and still get this error.  Anyone know what to do?

**Comment by krisdigitx** [comment]
this worked for me too....on fedora 23
╰─➤  sudo yum -y install libvirt-devel

**Comment by ghost** [comment]
i have fedora31 and i also have all dependencies installed, still can not make it work - any suggestion ?
