### ISSUE TITLE
Improve configuration of internal logging/debugging output

### ISSUE THREAD

**Issue by r10r** [jedi4ever/veewee#557]
Hi,

i noticed that the internal logging does not work in absent of ENV['VEEWEE_LOG'].
So specifying the *--debug* option does nothing without the environment variable.
I tried to make the logging/debugging more intuitive:

GmbH/veewee@315460b76133f0b0a4fc5f89999f424c94ed6d70

The VEEWEE_LOG environment variable is now used for the loglevel instead of 
the logger output target.  *--debug* sets the VEEWEE_LOG environment variable properly to "debug"  I removed the possibility to change the logger output as I think this is not needed.
Does anyone wants to change the output?

I'm happy to hear your feedback!

Cheers,
Ruben

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
