### ISSUE TITLE
Errors in console_type do not propagate to main thread, hanging veewee

### ISSUE THREAD

**Issue by jasonberanek** [jedi4ever/veewee#559]
Pull request #488 changed the call to send the boot sequence keystrokes from being executed in the main thread to being executed in a separate thread. The purpose of this change was to address the boot sequence being executed before the kickstart/preseed file was being served.

Wrapping the `self.console_type(boot_sequence)` in a thread results in errors raised by that method exiting that thread without any feedback to the main thread to perform appropriate recovery actions. Also, since the `kickstart_timeout` property is not used when starting the web servers to serve individual files, veewee will hang indefinitely waiting for the file to be retrieved. This behavior was observed when testing these changes with the in-work vsphere provider, which has explicit cases where VNC connection may fail. However, any error during console_type would trigger the same behavior.

I've investigated the following methods to fix this issue:

1. Adding error handling to detect any exception in the child thread and re-raising that error in the main thread does not appear to work based on how the WebBrick (used to serve the kickstart/preseed files) interacts with the main thread.

  a. Following the steps of 1 above, if WebBrick is started in a separate thread, by using `allow_for_http_request` rather than `wait_for_http_request`, this approach does work as expected.

2. Modifying the `self.handle_kickstart` call to start WebBrick instances in their own thread (so they are started before issuing the boot sequence), then calling `self.console_type(boot_sequence)` shows the same behavior of errors not being handled as expected, and veewee hanging.

@jedi4ever I don't see a clearly correct way to fix this, so I'm submitting as an issue rather than cutting code. The two options I see that are viable are 1a above, or reverting the changes from #488 completely (which would re-introduce what that change was attempting to correct). If you'd like to proceed with 1a above, I can put together a patch and issue a pull request.

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
