### ISSUE TITLE
undefined method 'size' for nil:NilClass

### ISSUE THREAD

**Issue by YujieDu** [jedi4ever/veewee#574]
I want to install veewee on windows7 use the command:
>gem install veewee
but get this error.

Some info:
>gem list
......
builder (3.1.4)
foreman (0.61.0)
gherkin (2.11.6 x86-mingw32, 2.11.5 x86-mingw32)
json (1.7.7, 1.5.4)
multi_json (1.5.0)
rake (10.0.3, 0.9.2.2)
vagrant (1.0.6)

>vboxmanage -v
4.2.6r82870

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
