### ISSUE TITLE
veewee requirements for running on Windows hosts

### ISSUE THREAD

**Issue by mfn** [jedi4ever/veewee#618]
I couldn't find any explicit documentation for running veewee under Windows. The documentation at https://github.com/jedi4ever/veewee/blob/master/doc/requirements.md and https://github.com/jedi4ever/veewee/blob/master/doc/installation.md is mostly clear to follow, but seems to expect to run under a more unix-y environment then Windows is.

Some pitfalls I discovered while trying to get veewee running:
- VirtualBox installation directory it not in the search path after installation, thus veewee fails when trying to remote VirtualBox via the `VBoxManage` command.<br>_Suggestion:_ document to add `C:\Program Files\Oracle\VirtualBox` (or whatever the installation path is) to the user search path.
- Certain unix-like tools are expected to be available to veewee or the user, the ones I encountered so far:
  - `tar` is required for running e.g. `veewee vbox export`
  - `ssh`: after finishing building a box it's suggested to the user to use `ssh` to login. Or use the command `veewee vbox ssh`. Either fails if there no prior `ssh` available in the search path.

Since the available ecosystem is quite diverse for Windows in this regard, there are probably multiple ways to get the proper tools available.

By the comment from installation.md, I built veewee instead of installing as a gem, I also installed Git for Windows which, after manual action is taken, can provide at least the two missing tools I mentioned.

Cygwin is another option. But I've had problems with Cygwin and mixed path in my approach which I want to elaborate quickly: I had a cygwin installation in my search path available, thus the full range of unix tools was available to me (`git`, `tar`, `ssh`). Ruby however is supposed to be installed from http://rubyinstaller.org/ which has no correlation to cygwin per se. When performing the suggested installation, I had an error with `bundle install` because Windows Ruby and Cygwin Git used different Windows path notions thus couldn't work together. Based on this problem I faced, I found it more predictable to a) don't have cygwin by default in my search path and b) make Git `bin\` path available to my search path. But in the end this is yet another personal preference.

Maybe for Windows user not having already set up a proper development environment, some "requirement suggestions" could be given.

(Most of this information is derive from my answer at https://github.com/jedi4ever/veewee/issues/612#issuecomment-15355515 )

**Comment by voltagex** [comment]
What do I need to do to build Linux VM images on a Windows host?

**Comment by mfn** [comment]
Closing, no longer user either veewee nor windows.
