### ISSUE TITLE
"Error downloading kickstart file" with OSX host and VMWare Fusion

### ISSUE THREAD

**Issue by datakurre** [jedi4ever/veewee#670]
Hi,

this is probably a problem with my OSX network configuration or VMWare Fusion configuration, but any help would be welcome.

I'm trying to build a new box for CentOS 6.4 64bit on OSX 10.8 host for VMWare Fusion 5.0.3. The build fails at downloading the kickstart file from the host machine with error:

```
ERROR: Error downloading http://192.168.174.1:7122/ks.cfg: Couldn't connect to server
```

If I fix `definition.rb` (or otherwise tweak veewee) to download the kickstart file using my host's **public ip** instead of `host_ip_as_seen_by_guest`, it works.

**Comment by CaseyLeask** [comment]
@datakurre I might have the same problem. Do you remember how you fixed it?
