### ISSUE TITLE
Run Veewee outside of source directory

### ISSUE THREAD

**Issue by shamrin** [jedi4ever/veewee#693]
Installed Veewee with rbenv (because rvm didn't work for me):

    $ git clone https://github.com/jedi4ever/veewee.git
    $ cd veewee/
    $ rbenv install 1.9.2-p320
    $ rbenv rehash
    $ rbenv local 1.9.2-p320
    $ rbenv rehash
    $ gem install bundler
    $ rbenv rehash
    $ bundle install

Veewee works locally:

    $ bundle exec veewee version
    Version : 0.3.7 - use at your own risk

But it doesn't work outside of its dir:

    $ cd ..
    $ bundle exec veewee version
    Could not locate Gemfile

How to run Veewee outside of its source dir? I'm new to Ruby/rbenv/gem/bundler, so it's likely the answer is simple. But I couldn't figure it out myself and [installation][]/[commands][] instructions are silent about it.

[installation]: https://github.com/jedi4ever/veewee/blob/master/doc/installation.md
[commands]: https://github.com/jedi4ever/veewee/blob/master/doc/commands.md

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
