### ISSUE TITLE
Finding Fusion boxes that aren't there

### ISSUE THREAD

**Issue by bkhl** [jedi4ever/veewee#694]
Using fission 0.4.0 installed by default by RVM/Gem, I ran into this issue:

https://github.com/thbishop/fission/issues/23

Instead checking out the development version of fission from github gives me a new one. fission seems to decide that it can't build, since the given box already exist. It doesn't, however, and using build --force or destroy gives me this:

```
$ veewee fusion destroy RHEL-6.3-x86_64
/Users/bnl/.rvm/gems/ruby-1.9.2-p320@veewee/bundler/gems/fission-a8fe3857e87c/lib/fission/vm.rb:528:in `all_running': uninitialized constant Fission::Action (NameError)
```

Maybe veewee needs to be updated to take into account how fission currently deals with listing extant boxes?

**Comment by symgryph** [comment]
I also get this error. Any fix?

**Comment by symgryph** [comment]
<script src="https://gist.github.com/symgryph/2bcc250f2b5064a1dcd3.js"></script>

**Comment by symgryph** [comment]
Here is the GIST of my output.

https://gist.github.com/symgryph/2bcc250f2b5064a1dcd3
