### ISSUE TITLE
Arch Linux box hangs at reboot

### ISSUE THREAD

**Issue by gkb** [jedi4ever/veewee#847]
I was trying to build an arch linux x86-64 box on Virtualbox 4.3.2, using Packer and veewee-to-packer, when the guest os simply hung. The provisioning script running/waiting when arch linux hung was `reboot.sh`.

On further investigation, I found that this issue could be caused [by the latest updates to systemd](https://bbs.archlinux.org/viewtopic.php?id=170756&p=2). But if there's any way to not run provisioning scripts that would cause it to go to that state, I'll be thrilled.

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
