### ISSUE TITLE
how to contribute ubuntu-12.04.3-server-amd64 parallels only template?

### ISSUE THREAD

**Issue by mkoryak** [jedi4ever/veewee#850]
Hi, 
I recently made an ubuntu-12.04.3-server-amd64 parallels template which currently lives here:

https://github.com/mkoryak/vagrant-parallels-ubuntu-12.04-lts/tree/master/definitions/parallels-ubuntu-12.04-server-amd64

I wanted to contribute it back to veewee but I cannot overwrite your 'ubuntu-12.04.3-server-amd64' definition because my version will not work with any other providers. The reason for this is that I had to remove the other provider's .sh files because they caused problems with missing files.

Let me know if you want my parallels only definition an under what name should i create the pull request?

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
