### ISSUE TITLE
fusion provider tries to use parallels

### ISSUE THREAD

**Issue by richardbowden** [jedi4ever/veewee#860]
On OSX 10.9 with VMWare Fusion and Parallels installed

When running "veewee fusion build 'u12043'" Parellels launches and gets into a mess.

if you run with -n "veewee fusion build 'bowdenbox-u12043' -n" everything works as expected.

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
