### ISSUE TITLE
get_mac_address fail on export : VM not ready

### ISSUE THREAD

**Issue by klepthys** [jedi4ever/veewee#931]
Can't really figure what is happening as it worked well until recently.

I have this error : 

```
VBoxManage: error: The object is not ready
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), component Console, interface IConsole, callee nsISupports
VBoxManage: error: Context: "COMGETTER(SharedFolders)(ComSafeArrayAsOutParam(folders))" at line 2185 of file VBoxManageInfo.cpp
```

As far as I can tell from the dump that follow, error seems to come from this : 

    VMState="stopping"

Doesn't makes sense to me, as this script previously checked : 

     Machine _machine-name_ is powered off cleanly

**Comment by mpapis** [comment]
closing as there was no feedback in three months, please let me know if you can provide more details and I will reopen
