### ISSUE TITLE
Automated Installation of Debian from CD/DVD image

### ISSUE THREAD

**Issue by metmajer** [jedi4ever/veewee#964]
Hi and thanks for this awesome project!

I would like to have my virtual machine be installed from a Debian 7.5 CD/DVD image to minimize downloads at installation time compared to the netboot variant. However, when I run veewee to create the box, the installation process requires additional keyboard inputs, e.g. to confirm that packages can be installed from a remote Debian mirror.

Any clues on how the boot command sequence from `veewee / templates / Debian-7.5.0-amd64-netboot / definition.rb` has to be altered to accomplish an installation that does not require manual interaction?

Thanks, Martin

**Comment by FunTimeCoding** [comment]
@metmajer did you get this to work?

**Comment by metmajer** [comment]
@FunTimeCoding I think the solution was to use a Debian-netinst.iso which does not require these inputs.

**Comment by FunTimeCoding** [comment]
thank you
